In [1]:
import numpy

In [2]:
numpy.__version__

'1.19.2'

In [3]:
import numpy as np

## numpy.array

In [4]:
nparr = np.array([i for i in range(10)])

In [5]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [7]:
nparr.dtype

dtype('int64')

In [10]:
nparr[5] = 5.1
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
nparr.dtype

dtype('int64')

In [13]:
nparr2 = np.array([1, 2, 3.1])

In [14]:
nparr2.dtype

dtype('float64')

## 创建numpy array

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [21]:
np.full(shape=(3, 5), fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

## arange

In [22]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [23]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.arange(0, 1, .2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [29]:
np.linspace(0, 20, 10) # 最后一个参数代表个数， 是个闭区间

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [30]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [37]:
np.random.randint(0, 10)   #前闭后开

0

In [38]:
np.random.randint(0, 10, 10)

array([0, 9, 4, 7, 6, 1, 0, 4, 4, 2])

In [39]:
np.random.randint(0, 10, (2, 3))

array([[8, 0, 4],
       [0, 6, 6]])

In [40]:
np.random.randint(4, 8, size=10)

array([4, 4, 4, 5, 5, 4, 6, 6, 6, 6])

In [41]:
np.random.randint(4, 8, size=(3, 5))

array([[5, 6, 6, 6, 6],
       [7, 4, 5, 5, 7],
       [7, 4, 6, 7, 5]])

In [46]:
np.random.seed(666) # 设定随机种子， 得到相同的随机数
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [47]:
np.random.seed(666) 
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [48]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 7, 4],
       [6, 4, 7, 5, 6],
       [4, 7, 5, 5, 5]])

In [49]:
np.random.randint(4, 8, size=(3, 5))  # 验证一下，随机种子只能用一次，再次使用就得再定义

array([[4, 7, 4, 4, 4],
       [4, 4, 4, 6, 6],
       [6, 7, 4, 5, 4]])

In [50]:
np.random.random() # 数值在0-1之间, 均匀分布

0.34976190475749336

In [52]:
np.random.random(10)

array([0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949,
       0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981])

In [53]:
np.random.random((2, 3))

array([[0.75366384, 0.66673747, 0.87287954],
       [0.52109719, 0.75020425, 0.32940234]])

In [54]:
np.random.normal() #均值=0，方差=1，正态分布

0.1121217025535024

In [57]:
np.random.normal(10, 100, (3, 5)) #均值为10，方差=100

array([[  13.18538839,   -9.20628514,   88.6112843 , -159.04631421,
         -88.87390714],
       [  41.39856302,   49.63856739,   67.65658375,    2.98059308,
         101.25043617],
       [ 110.4704966 ,   51.85992895, -142.90245423,  102.48753198,
          28.3054285 ]])

In [58]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution