In [2]:
import numpy as np

In [3]:
x = np.arange(10)

In [4]:
x.ndim

1

In [5]:
X = np.arange(15).reshape(3, 5)

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
X[0][0]

0

In [12]:
X[0, 0] # 推荐这种

0

In [13]:
x[0:5]

array([0, 1, 2, 3, 4])

In [15]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [17]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [18]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [19]:
subX = X[:2, :3]

In [20]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [21]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [22]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [23]:
subX = X.copy()

In [24]:
subX

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [25]:
subX[0, 0] = 200
subX

array([[200,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [26]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

## reshape

In [27]:
x.ndim

1

In [28]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
y = x.reshape(2, 5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
y[0, 0] = 100
y

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [32]:
x

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [33]:
b = x.reshape(1, 10)

In [34]:
b.ndim

2

In [35]:
c = x.reshape(10, -1)

In [36]:
c.shape

(10, 1)

In [37]:
c

array([[100],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [39]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [40]:
np.stack([x, y])

array([[1, 2, 3],
       [3, 2, 1]])

In [41]:
a = np.arange(1, 7).reshape(2, 3)

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
np.stack([a, a])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [46]:
np.concatenate([a, a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [47]:
 z = np.array([6, 6, 6])

In [51]:
a2 = np.concatenate([a, z.reshape(1, -1)])

In [52]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [6, 6, 6]])

In [54]:
np.vstack([a, z])

array([[1, 2, 3],
       [4, 5, 6],
       [6, 6, 6]])

In [55]:
b = np.full((2, 2), 100)
b

array([[100, 100],
       [100, 100]])

In [57]:
np.hstack([a, b])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [61]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.split(x, [3, 7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [63]:
np.split(x, [3, 6, 7, 9])

[array([0, 1, 2]), array([3, 4, 5]), array([6]), array([7, 8]), array([9])]

In [67]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
A1, A2 = np.split(A, [2])
A1, A2

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [75]:
np.split(A, [2], axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [76]:
np.vsplit(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [78]:
np.hsplit(A, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [79]:
X, y = np.hsplit(A, [-1])
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [80]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [81]:
y[:, 0]

array([ 3,  7, 11, 15])