In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])

In [3]:
a ** 2

array([0, 1, 4])

In [4]:
np.abs(a)

array([0, 1, 2])

In [5]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743])

In [9]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [11]:
np.power(a, 3)

array([0, 1, 8])

In [13]:
np.log2(a)

<ipython-input-13-c177bbf86267>:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(a)


array([-inf,   0.,   1.])

In [17]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [20]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [21]:
A * B # wise-multi

array([[ 0, 10],
       [20, 30]])

In [22]:
np.dot(A, B) #matrix-multiply

array([[10, 10],
       [50, 50]])

In [24]:
A.T

array([[0, 2],
       [1, 3]])

In [25]:
A

array([[0, 1],
       [2, 3]])

# 向量 矩阵

In [27]:
v = np.array([1, 2])

In [28]:
A

array([[0, 1],
       [2, 3]])

In [29]:
v + A

array([[1, 3],
       [3, 5]])

In [30]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [31]:
v * A

array([[0, 2],
       [2, 6]])

In [32]:
v.dot(A)

array([4, 7])

In [33]:
A.dot(v)

array([2, 8])

# 矩阵的 逆

In [34]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [36]:
pA = np.linalg.pinv(A) #原矩阵 * 这个矩阵等于 方阵
pA

array([[-1.50000000e+00,  5.00000000e-01],
       [ 1.00000000e+00,  5.55111512e-17]])

In [37]:
A * pA

array([[-0.00000000e+00,  5.00000000e-01],
       [ 2.00000000e+00,  1.66533454e-16]])