In [1]:
import numpy as np

In [2]:
L = np.random.random(100)

In [3]:
L

array([0.43672311, 0.7986266 , 0.82316388, 0.68483427, 0.18853726,
       0.85262084, 0.20085642, 0.09819141, 0.92099677, 0.83334913,
       0.05861482, 0.13862941, 0.00376128, 0.78120474, 0.85835213,
       0.86940845, 0.12389177, 0.01893847, 0.27498413, 0.45157281,
       0.71851576, 0.71455113, 0.39540621, 0.25517748, 0.1881558 ,
       0.91756383, 0.81978908, 0.99825832, 0.34066211, 0.73127878,
       0.73294074, 0.6696313 , 0.10435956, 0.48844971, 0.92090537,
       0.7881816 , 0.9285349 , 0.42057013, 0.4462591 , 0.60063238,
       0.1178282 , 0.1900064 , 0.90457782, 0.8075957 , 0.1134976 ,
       0.29214853, 0.94735632, 0.54160773, 0.91758809, 0.3007111 ,
       0.20196159, 0.91445701, 0.92903258, 0.00314479, 0.31348315,
       0.14815506, 0.51381171, 0.002881  , 0.42068073, 0.88572004,
       0.84300399, 0.45604939, 0.00386223, 0.78573492, 0.13095373,
       0.37450786, 0.31634993, 0.0527956 , 0.98515831, 0.78808623,
       0.39325715, 0.99327954, 0.49764436, 0.98419789, 0.91995

In [9]:
%timeit sum(L)

13.8 µs ± 161 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
%timeit np.sum(L)

2.45 µs ± 19.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
np.min(L)

0.002881000637972364

In [12]:
np.max(L)

0.9982583224484844

In [13]:
x = np.arange(16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.sum(x)

120

In [15]:
np.max(x)

15

In [16]:
np.sum(x, axis=0)

array([24, 28, 32, 36])

In [17]:
np.sum(x, axis=1)

array([ 6, 22, 38, 54])

In [18]:
np.max(x, axis=0)

array([12, 13, 14, 15])

In [19]:
np.prod(x+1)

20922789888000

In [20]:
np.mean(x) # 平均

7.5

In [21]:
np.median(x) # 中位数

7.5

In [22]:
np.percentile(x, q=50) #百分位

7.5

In [23]:
np.percentile(x, q=80)

12.0

In [24]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(x, percent))

0.0
3.75
7.5
11.25
15.0


In [25]:
np.std(x)

4.6097722286464435

In [26]:
np.var(x)

21.25

# 索引

In [27]:
np.argmin(x) # 返回最小值的索引

0

In [28]:
np.argmax(x)

15

# 排序和使用索引

In [29]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
np.random.shuffle(x)
x

array([ 2, 10,  9, 11,  0, 12,  5, 15, 14,  1, 13,  7,  3,  6,  4,  8])

In [31]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
x

array([ 2, 10,  9, 11,  0, 12,  5, 15, 14,  1, 13,  7,  3,  6,  4,  8])

In [33]:
x.sort() #注意差别

In [34]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
X = np.random.randint(10, size=(4, 4))
X

array([[9, 1, 1, 7],
       [3, 3, 2, 6],
       [5, 1, 7, 4],
       [7, 2, 0, 4]])

In [39]:
np.sort(X)

array([[1, 1, 7, 9],
       [2, 3, 3, 6],
       [1, 4, 5, 7],
       [0, 2, 4, 7]])

In [41]:
np.sort(X, axis=0)

array([[3, 1, 0, 4],
       [5, 1, 1, 4],
       [7, 2, 2, 6],
       [9, 3, 7, 7]])

In [52]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
np.random.shuffle(x)
x

array([12,  3,  4, 10, 11,  8,  6,  7, 15,  9,  2, 13,  0, 14,  5,  1])

In [54]:
np.argsort(x) # 索引排序

array([12, 15, 10,  1,  2, 14,  6,  7,  5,  9,  3,  4,  0, 11, 13,  8])

In [55]:
np.partition(x, 10)

array([ 3,  1,  4,  5,  0,  2,  6,  7,  9,  8, 10, 12, 11, 13, 14, 15])

In [56]:
np.argpartition(x, 10)

array([ 1, 15,  2, 14, 12, 10,  6,  7,  9,  5,  3,  0,  4, 11, 13,  8])

In [57]:
X

array([[9, 1, 1, 7],
       [3, 3, 2, 6],
       [5, 1, 7, 4],
       [7, 2, 0, 4]])

In [59]:
np.argsort(X, axis=1)

array([[1, 2, 3, 0],
       [2, 0, 1, 3],
       [1, 3, 0, 2],
       [2, 1, 3, 0]])

In [61]:
np.argsort(X, axis=0)

array([[1, 0, 3, 2],
       [2, 2, 0, 3],
       [3, 3, 1, 1],
       [0, 1, 2, 0]])